USE [#DATABASE_NAME#]
GO
ALTER INDEX ALL ON [Data].[Customer] REORGANIZE
ALTER INDEX ALL ON [Data].[Store] REORGANIZE
ALTER INDEX ALL ON [Data].[Date] REORGANIZE
ALTER INDEX ALL ON [Data].[Product] REORGANIZE
ALTER INDEX ALL ON [Data].[Orders] REORGANIZE
ALTER INDEX ALL ON [Data].[OrderRows] REORGANIZE
GO
DBCC SHRINKFILE (N'#DATABASE_NAME#' , 0)
GO
DBCC SHRINKFILE (N'#DATABASE_NAME#' , 0)
GO
DBCC SHRINKFILE (N'#DATABASE_NAME#' , 0)
GO
DBCC SHRINKFILE (N'#DATABASE_NAME#' , 0)
GO
DBCC SHRINKFILE (N'#DATABASE_NAME#' , 0)
GO
DBCC SHRINKFILE (N'#DATABASE_NAME#' , 0)
GO
DBCC SHRINKFILE (N'#DATABASE_NAME#' , 0)
GO
DBCC SHRINKFILE (N'#DATABASE_NAME#' , 0)
GO
DBCC SHRINKFILE (N'#DATABASE_NAME#' , 0)
GO
DBCC SHRINKFILE (N'#DATABASE_NAME#' , 0)
GO
DBCC SHRINKFILE (N'#DATABASE_NAME#' , 0)
GO
DBCC SHRINKFILE (N'#DATABASE_NAME#' , 0)
GO
DBCC SHRINKFILE (N'#DATABASE_NAME#' , 0)
GO
DBCC SHRINKDATABASE(N'#DATABASE_NAME#' )
GO
DBCC SHRINKFILE (N'#DATABASE_NAME#' , 0)
GO
DBCC SHRINKFILE (N'#DATABASE_NAME#_log' , 0, TRUNCATEONLY)
GO
