BACKUP DATABASE [#DATABASE_NAME#] 
TO DISK = N'#SQLBACKUP_FOLDER#\#DATABASE_NAME#.bak' 
WITH NOFORMAT, INIT,  NAME = N'#DATABASE_NAME#-Full Database Backup', 
     SKIP, NOREWIND, NOUNLOAD, COMPRESSION,  STATS = 10
GO

USE [master]
GO
ALTER DATABASE [#DATABASE_NAME#] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
EXEC master.dbo.sp_detach_db @dbname = N'#DATABASE_NAME#'
